const colors = {
    "homebackgroundcolor": '#0A1924',
    "menubackgroundcolor": '#29363F',
    "defaulttextcolor": "#BDB9AD",
    "whitetext": "#FFFFFF",
    "notificationcolor":"#EA3232",
    "servicebackground":"#FEC107",
    "completetask":"#18A7E0",
    "cancletetask":"#BDB9AD",
    "loadercolers":"#FFFFFF",

    "drawerheaderTintColor":"#FFFFFF",
    "headerstylebgColor":"#ba68c8",
    "draweractiveTintColor":"#ba68c8",
    "drawerinactiveTintColor":"gray",
    "drawertxtColor":"#ba68c8",
    "draweritemStyle":"#FFFFFF",
    "drawerlabelStyle":"#ba68c8",

    "linearGradientColor1":"#ED0285",
    "linearGradientColor2":"#ffffff",
    "activityIndicatorColor":"#FFFFFF",
    "actionbtnColor":"#ba68c8",

    "customerDetailsHaderColors":"#FFFFFF",
    "customerDetailsHaderTintColor":"black",
    "customerDetailsContainer":"#FFFFFF",

    "customerDetailsCardShadowColors":"#999",
    "customerDetailsBorderColors":"#ccc",
    //"customerDetailsBorderColors":"#ba68c8",
    "createpostBorderColors1":"#ba68c8",
    "createpostBorderColors2":"#1C87C9",
    "customerDetailsbgColors":"#FFFFFF",
    "customerDetailsCardTitleColors":"black",
    "customerDetailsCardTitle2Colors":"#ED0285",
    "customerDetailsCardTitle3Colors":"#ED0285",
    "customerDetailsCardDetailsColors":"#444",

    "homebgColors":"#FFFFFF",
    "homeslidebgColors":"transparent",
    "aboutbgColors":"#FFFFFF",
    "contactbgColors":"#FFFFFF",
    "profilebgColors":"#FFFFFF",
    "settingbgColors":"#FFFFFF",
   
    "customesideMenuContainerbgcolors":"#FFFFFF",
    "customesideMenuContainercolors":"#FFFFFF",
    "customesideMenuprofileHeaderbgcolors":"#ba68c8",
    "csmprofileHeaderPicCirclecolors":"#FFFFFF",
    "csmprofileHeaderPicCirclebgcolors":"#FFFFFF",
    "csmprofileHeaderTextcolors":"#FFFFFF",
    "csmprofileHeaderLinecolors":"#e2e2e2",

    "splashscreentitlecolors":"#FFFFFF",

    "templatescontainerbgcolors":"#FFFFFF",
    "templateshadowcardcolors":"#999",
    "templatescardInfobordercolors":"#ccc",
    "templatescardInfobgcolors":"#FFFFFF",
    "templatescardViewbordercolors":"#ccc",
    "templatescardViewbgcolors":"#ba68c8",
    "templatescardDetailscolors":"#444",

    "templatesactionButtonIconcolors":"#FFFFFF",
    "homeactiveDotcolors":"#FFFFFF",

    "writerMemorycolors":"#1C87C9",
    "writerMemoryTextcolors":"#ffff",
    "multiinputbordercolors":"#ba68c8",
    "buttonStylebgcolors":"#1C87C9",
    "buttonStylecolors":"#ffff",
    "buttonStylebordercolors":"#7DE24E",
    "buttonTextcolors":"#ffff",
    "storyTitlecolors":"grey",
    "TextInputplaceholderTextColor":"#8b9cb5",
    "TextInputunderlineColorAndroid":"#ba68c8",
    
    "editProfileHaderbgColors":"#FFFFFF",
    "editProfileHaderTintColors":"black",
    "editProfileTextInputplaceholderTextColor":"black",
    "editProfileTextInputunderlineColorAndroid":"lightgrey",
    "editProfilebuttonTextcolors":"#ffff",
    "editProfilebuttonbgcolors":"#00BFFF",
    "editProfilebuttonStylecolors":"#ffff",
    "editProfilebuttonStylebordercolors":"#7DE24E",
    "editProfileAlltxtcolors":"black",
    "editProfileAllTitlecolors":"#00BFFF",
    "editProfileavatarColors":"#FFFFFF",
    "editProfilecameraavatarColors":"#FFFFFF",
    "editProfileNameColors":"#696969",

    "ProfileavatarborderColors":"#FFFFFF",
    "ProfileNameColors":"#696969",
    "ProfileEmailvalueTitleColors":"#00BFFF",
    "templatebtniconColors":"white",
    "templatebtnColors":"#ba68c8",
    "logincontainerbgColors":"#66CCFF",
    "logininnercardborderColors":"#EEF6FE",
    "logininnercardbgColors":"#EEF6FE",

    "loginbuttonStylebgColors":"#EEF6FE",
    "loginbuttonStyleColors":"#61B4FF",
    "loginbuttonStyleborderColors":"#61B4FF",

    "loginbutton2StylebgColors":"#EEF6FE",
    "loginbutton2StyleColors":"#61B4FF",
    "loginbutton2StyleborderColors":"#61B4FF",

    "loginbuttonTextColors":"#61B4FF",
    "RegisterHaderbgColors":"#FFFFFF",
    "RegisterHaderTintColors":"black",
    "RegisterlinearGradientColor1":"#99FFFF",
    "RegisterlinearGradientColor2":"#99CCFF",

    "RegisterineercardInfoColor":"white",
    "RegisterbuttonStylebgColor":"#288FFF",
    "RegisterbuttonStyleborderColors":"#288FFF",
    "RegisterbuttonTextColors":"white",
    "RegisterAllTextborderColors":"grey",
    "RegisterSubTitleColors":"grey",
    "RegisterAllLabelColors":"grey",
    "EditProfileBottomSheetbgColors":"white",
    "EditProfileBottomSheetaAllPanelColors":"#003470",
    "EditProfileBottomSheetpanelButtonTitleColors":"white",
    "CreatePostbtnFileUploadColors":"grey",
    "templatecardiconColors":"#ba68c8",

    "ModalcontentColors":"pink",
    "ModalarrowColors":"pink",
    "FilterIcnColors":"white",
    "AllDrawerIconColors":"ba68c8",
    "ModaltxtColors":"white",
    "ModalBtnlColors":"#003470",
    "FilterIconColors":"white",
    "heartIconRedColors":"red",
    "CustDetailsIconRedColors":"red",
    "CustDetailsIcongreyColors":"grey",
    "CustDetailsAllIconTextColors":"black",

};
export default colors;