export default AppString = {
  //Common
  INTERNET_CONNECTION: 'Please Check Your Internet Connection.',
  APP_NAME: 'eCompendium',
  NETWORK_ERROR: 'Network Error Please Check Internet',
  LOGIN_EMAIL_REQUIRED: "Please enter email",
  VALIDATE_NAME_REQUIRED_FIRSTNAME: 'Please Enter first name',
  VALIDATE_NAME_REQUIRED_LASTNAME: 'Please Enter last name',
  VALIDATE_EMAIL_INVALID: 'Please enter valid email',
  VALIDATE_PASSWORD_REQUIRED: 'Please enter password',
  VALIDATE_CONFIRM_PASSWORD_REQUIRED: 'Please Enter Conform Password',
  VALIDATE_PASSWORD_CONFIRM_PASSWORD_REQUIRED: 'Please Enter Password & Conform Password same',
  SIGNUP_SUCCESS_MESSAGE: 'Registration has been successfully done!',
  VALIDATE_FEED_SELECT: 'No athelete selected',
  VALIDATE_PASSWORD_NOT_MATCH_REQUIRED: 'Password & Conform Password is Not Match',
  VALIDATE_OTP_REQUIRED: 'Please Enter Valid OTP',
  VALIDATE_IMAGE_REQUIRED: 'Please Select Image',
  VALIDATE_DATA_UPDATE: 'Data Update Fail',
  VALIDATE_TITLE_NAME: 'Please Enter Title',
  VALIDATE_PRICE: 'Please Enter Price',
  VALIDATE_MODIFIER: 'Please Enter Modifier',
  VALID_PRICE: 'Please Enter Valid Price',
  VALIDATE_DESCRIPTION: 'Please Enter Description',
  INFORMATION_UPDATE_SUCCESS: 'Information Update Successfully',
  LOGIN_USERNAME_PASSWORD: 'Invalid email or password',
  SOMTHING_WRONG: 'Somthing Wrong',
  appUpdateMsg: 'You are using an older version of app please update your app.',
  ok: 'Ok',
  cancel: 'Cancel',
  update: 'Update',
  //force update
  appleConnectUrl: 'https://itunesconnect.apple.com/login',
  androidConnect: 'https://play.google.com/store?hl=en',
  updateAlert: 'eCompendium App needs an update',
  downLoadUpdateData: 'To use this app, download the latest version',
  Internet: "Internet",
  InternetDescription: "To access the internet please follow these steps:",
  Preview: "Preview",
  Discard: "Discard",
  Save: "Save",
  Phone:"Phone",
  PhoneDescription:"To use the phone please follow these steps:",
  step1WififAccess : 'Search for the network name: “Hotel Wifi” and press connect',
  step2WififAccess : 'You’re now connected!',
  step1PhoneAccess : 'Turn on the device',
  step2PhoneAccess : 'Enter number and press dial',
  AddTitle: 'Add Title',
  AddDesc: 'Add Description',
  AddPrice:'$33',
  NoDataAvail:'No Data Found',

  ItemTitle: "Please Enter Item Title",
  ItemDescription: "Please Enter Item Description",
  Titlelable: "Title",
  Descriptionlable: "Description",
  ItemTitleName: "Eggs Benedict",
  ItemTitleDescription: "Description Description Description Description Description Description Description Description",
  ItemPriceName: "$12",
  AddPhoto: "+ Add Photo",
  Price: "Price",
  AddModifiers: "Add modifiers",
  Add: "Add",
  CreateModifier: "+ Create Modifier",
  SpacialOffer: "Special Offers",
  SpacialOfferdescription: "Looking for something to do? Choose one of our exciting offers below!",
  AddCategory: "+ Add Category",
  Rooms: "Rooms",
  Room: "Room",
  Filter: "Filter",
  View: "View",
  Table: "Table",
  Edit: "Edit",
  Connect: "Contact",
  Login: 'Login',
  SaveButton: 'Save', 
  DashBoard:"DashBoard",
  Dining:"Dining",
  DiningPreview:"DiningPreview",
  Promotions:"Promotions",
  LocalRestaurant:"LocalRestaurant",
  Housekeeping:"Housekeeping",
  Internet:"Internet",
  InternetPreview:"InternetPreview",
  Phone:"Phone",
  LocalRestoPreview:"LocalRestoPreview",
  Main:"Main",
  PhonePreview:"PhonePreview",
  PromotionsPreview:"PromotionsPreview",


  //Make My Memo Title
  SplashScreenTitle1:"WELCOME TO",
  SplashScreenTitle2:"MAKE MY MEMORIES",
  SidebarMenuTitle:"Make My Memories",
  TemplateTitle:"MAKE MY MEMO",

  homeTitle:"Home",
  aboutTitle:"About",
  profileTitle:"Profile",
  settingTitle:"Settings",
  contactTitle:"Contact",
  customerDetailsTitle:"My Details"


};
